# Generated by Django 3.1.3 on 2020-12-02 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_character_dm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxType', models.CharField(choices=[('name', 'Name'), ('nameNumber', 'Name & Number'), ('nameNumberInf', 'Name & Number Calculator'), ('nameNumberRange', 'Name & Number Calculator w/range'), ('nameDice', 'Name & Dice'), ('nameShortDesc', 'Name & Short Description'), ('nameLongDesc', 'Name & Long Description')], max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('text', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('longText', models.TextField(blank=True, null=True)),
                ('minNum', models.IntegerField(blank=True, null=True)),
                ('maxNum', models.IntegerField(blank=True, null=True)),
                ('positionX', models.IntegerField()),
                ('positionY', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.character')),
            ],
        ),
    ]
